spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:clientdb
  application:
    name: client-query-service
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
  config:
    import: "optional:consul:"
  jpa:
    show-sql: 'true'
server:
  port: '8081'
