spring:
  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTION
    discovery:
      enabled: 'true'
  application:
    name: gateway-service
server:
  port: '8888'
eureka:
  instance:
    prefer-ip-address: 'true'

